export 'pages/forex.dart';
export 'pages/favourite.dart';
export 'body.dart';
export 'main_tab.dart';
export 'pages/commodities.dart';
export 'pages/crypto.dart';
export 'pages/futures.dart';
export 'pages/indicies.dart';
export 'pages/stock.dart';
